# Generated by Django 6.0.5 on 2026-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genres', models.CharField(blank=True, help_text='Comma-separated genre interests', max_length=500)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('thriller', 'Thriller'), ('scifi', 'Sci-Fi'), ('romance', 'Romance'), ('biography', 'Biography'), ('children', "Children's"), ('academic', 'Academic'), ('selfhelp', 'Self-Help'), ('art', 'Art & Photography'), ('cooking', 'Cooking & Food'), ('travel', 'Travel')], default='fiction', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
