from decimal import Decimal

from django.core.management.base import BaseCommand

from store.models import Book


BOOKS = [
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "genre": "fiction",
        "price": "399.00",
        "stock": 18,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
        "description": "A moving novel about choices, regret, and the many lives a reader can imagine.",
    },
    {
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "genre": "fiction",
        "price": "375.00",
        "stock": 17,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
        "description": "A powerful story of friendship, betrayal, forgiveness, and family across changing times.",
    },
    {
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "genre": "fiction",
        "price": "425.00",
        "stock": 13,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
        "description": "A lyrical wartime novel about words, courage, and the people who keep hope alive.",
    },
    {
        "title": "Sapiens",
        "author": "Yuval Noah Harari",
        "genre": "nonfiction",
        "price": "599.00",
        "stock": 15,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
        "description": "A wide-ranging history of humankind, from early humans to modern society.",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "genre": "nonfiction",
        "price": "499.00",
        "stock": 14,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
        "description": "A striking memoir about learning, survival, family, and building an independent life.",
    },
    {
        "title": "The Psychology of Money",
        "author": "Morgan Housel",
        "genre": "nonfiction",
        "price": "349.00",
        "stock": 26,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
        "description": "Short lessons on wealth, behavior, risk, patience, and better financial decisions.",
    },
    {
        "title": "The Silent Patient",
        "author": "Alex Michaelides",
        "genre": "thriller",
        "price": "349.00",
        "stock": 20,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
        "description": "A psychological thriller about silence, obsession, and a shocking final reveal.",
    },
    {
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "genre": "thriller",
        "price": "399.00",
        "stock": 18,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
        "description": "A sharp domestic thriller built on secrets, media pressure, and dangerous deception.",
    },
    {
        "title": "The Girl with the Dragon Tattoo",
        "author": "Stieg Larsson",
        "genre": "thriller",
        "price": "450.00",
        "stock": 12,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg",
        "description": "A dark mystery involving corruption, family secrets, and a brilliant investigator.",
    },
    {
        "title": "Dune",
        "author": "Frank Herbert",
        "genre": "scifi",
        "price": "499.00",
        "stock": 16,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
        "description": "A landmark science fiction epic of politics, ecology, prophecy, and power.",
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "genre": "scifi",
        "price": "550.00",
        "stock": 15,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
        "description": "A clever space survival adventure about science, memory, friendship, and saving Earth.",
    },
    {
        "title": "Neuromancer",
        "author": "William Gibson",
        "genre": "scifi",
        "price": "399.00",
        "stock": 11,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
        "description": "A cyberpunk classic filled with hackers, artificial intelligence, and a neon future.",
    },
    {
        "title": "Book Lovers",
        "author": "Emily Henry",
        "genre": "romance",
        "price": "329.00",
        "stock": 14,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780593334836-L.jpg",
        "description": "A smart romantic comedy about rival publishing professionals and second chances.",
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "genre": "romance",
        "price": "199.00",
        "stock": 30,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
        "description": "A beloved classic about wit, class, family expectations, and slow-burning love.",
    },
    {
        "title": "The Love Hypothesis",
        "author": "Ali Hazelwood",
        "genre": "romance",
        "price": "399.00",
        "stock": 16,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780593336823-L.jpg",
        "description": "A cheerful campus romance with fake dating, science, trust, and charming tension.",
    },
    {
        "title": "Becoming",
        "author": "Michelle Obama",
        "genre": "biography",
        "price": "650.00",
        "stock": 12,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
        "description": "A personal memoir about identity, public life, family, and purpose.",
    },
    {
        "title": "Steve Jobs",
        "author": "Walter Isaacson",
        "genre": "biography",
        "price": "699.00",
        "stock": 10,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
        "description": "A detailed portrait of creativity, technology, leadership, intensity, and innovation.",
    },
    {
        "title": "Wings of Fire",
        "author": "A. P. J. Abdul Kalam",
        "genre": "biography",
        "price": "299.00",
        "stock": 24,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg",
        "description": "An inspiring life story of learning, discipline, science, service, and ambition.",
    },
    {
        "title": "Charlotte's Web",
        "author": "E. B. White",
        "genre": "children",
        "price": "249.00",
        "stock": 25,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780061124952-L.jpg",
        "description": "A beloved children's classic about friendship, kindness, and courage.",
    },
    {
        "title": "Matilda",
        "author": "Roald Dahl",
        "genre": "children",
        "price": "299.00",
        "stock": 20,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg",
        "description": "A funny, warm story about a brilliant young reader with courage and imagination.",
    },
    {
        "title": "Harry Potter and the Philosopher's Stone",
        "author": "J. K. Rowling",
        "genre": "children",
        "price": "499.00",
        "stock": 18,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780747532699-L.jpg",
        "description": "A magical school adventure about friendship, bravery, discovery, and belonging.",
    },
    {
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen",
        "genre": "academic",
        "price": "1200.00",
        "stock": 8,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780262046305-L.jpg",
        "description": "A comprehensive academic reference for algorithms and data structures.",
    },
    {
        "title": "Concepts of Physics Volume 1",
        "author": "H. C. Verma",
        "genre": "academic",
        "price": "520.00",
        "stock": 20,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9788177091878-L.jpg",
        "description": "A clear physics textbook for fundamentals, examples, and exam preparation.",
    },
    {
        "title": "Campbell Biology",
        "author": "Lisa A. Urry",
        "genre": "academic",
        "price": "1450.00",
        "stock": 7,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780134093413-L.jpg",
        "description": "A respected biology reference for students, diagrams, concepts, and review.",
    },
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "genre": "selfhelp",
        "price": "450.00",
        "stock": 22,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        "description": "A practical guide to building better habits through small, repeatable changes.",
    },
    {
        "title": "Deep Work",
        "author": "Cal Newport",
        "genre": "selfhelp",
        "price": "399.00",
        "stock": 21,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
        "description": "A focused guide to concentration, meaningful work, fewer distractions, and better output.",
    },
    {
        "title": "The 7 Habits of Highly Effective People",
        "author": "Stephen R. Covey",
        "genre": "selfhelp",
        "price": "499.00",
        "stock": 19,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
        "description": "A classic framework for personal leadership, priorities, relationships, and growth.",
    },
    {
        "title": "Ways of Seeing",
        "author": "John Berger",
        "genre": "art",
        "price": "299.00",
        "stock": 11,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780141035796-L.jpg",
        "description": "A concise classic on visual culture, art, images, and how we interpret them.",
    },
    {
        "title": "The Story of Art",
        "author": "E. H. Gombrich",
        "genre": "art",
        "price": "899.00",
        "stock": 9,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780714832470-L.jpg",
        "description": "A readable survey of art history, artists, movements, and visual ideas.",
    },
    {
        "title": "Understanding Exposure",
        "author": "Bryan Peterson",
        "genre": "art",
        "price": "650.00",
        "stock": 12,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781607748502-L.jpg",
        "description": "A practical photography guide to aperture, shutter speed, light, and composition.",
    },
    {
        "title": "Salt, Fat, Acid, Heat",
        "author": "Samin Nosrat",
        "genre": "cooking",
        "price": "799.00",
        "stock": 9,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781476753836-L.jpg",
        "description": "An approachable cooking guide built around four essential elements of flavor.",
    },
    {
        "title": "The Food Lab",
        "author": "J. Kenji Lopez-Alt",
        "genre": "cooking",
        "price": "1200.00",
        "stock": 8,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780393081084-L.jpg",
        "description": "A science-minded cookbook packed with techniques, explanations, and reliable recipes.",
    },
    {
        "title": "Indian-ish",
        "author": "Priya Krishna",
        "genre": "cooking",
        "price": "749.00",
        "stock": 10,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9781328482471-L.jpg",
        "description": "Fresh Indian-inspired recipes for home cooking, family meals, and everyday flavor.",
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "genre": "travel",
        "price": "299.00",
        "stock": 19,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
        "description": "A journey story about dreams, destiny, travel, and listening to one's heart.",
    },
    {
        "title": "Into the Wild",
        "author": "Jon Krakauer",
        "genre": "travel",
        "price": "350.00",
        "stock": 15,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780385486804-L.jpg",
        "description": "A gripping travel narrative about wilderness, freedom, risk, and searching for meaning.",
    },
    {
        "title": "Vagabonding",
        "author": "Rolf Potts",
        "genre": "travel",
        "price": "399.00",
        "stock": 13,
        "cover_url": "https://covers.openlibrary.org/b/isbn/9780812992182-L.jpg",
        "description": "A thoughtful guide to long-term travel, simplicity, planning, and seeing the world well.",
    },
]


class Command(BaseCommand):
    help = "Seed useful books across every storefront category."

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for item in BOOKS:
            _, created = Book.objects.update_or_create(
                title=item["title"],
                author=item["author"],
                defaults={
                    "genre": item["genre"],
                    "price": Decimal(item["price"]),
                    "stock": item["stock"],
                    "cover_url": item["cover_url"],
                    "description": item["description"],
                },
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded books complete: {created_count} created, {updated_count} updated."
            )
        )
